In [1]:
# Import Dependencies
import pandas as pd

In [26]:
shelter_csv = "cleaned_data.csv"

In [27]:
shelter_df = pd.read_csv(shelter_csv)

In [28]:
shelter_df.head()

,breed,outcome_type,outcome_age_(days),Cat/Kitten (outcome),outcome_month,outcome_year
0,domestic shorthair,Transfer,14,Kitten,7,2014
1,domestic shorthair,Adoption,30,Kitten,8,2014
2,domestic shorthair,Adoption,90,Kitten,6,2014
3,domestic mediumhair,Return to Owner,365,Cat,3,2014
4,domestic shorthair,Transfer,21,Kitten,1,2014

In [29]:
shelter_df.columns

Index(['breed', 'outcome_type', 'outcome_age_(days)', 'Cat/Kitten (outcome)',
       'outcome_month', 'outcome_year'],
      dtype='object')

In [36]:
shelter_df["Cat/Kitten (outcome)"].value_counts()

Kitten    17400
Cat       12021
Name: Cat/Kitten (outcome), dtype: int64

In [32]:
reduced_df = shelter_df.loc[:, ["outcome_age_(days)", "breed", "outcome_type"]]
reduced_df

       outcome_age_(days)                breed     outcome_type
0                      14   domestic shorthair         Transfer
1                      30   domestic shorthair         Adoption
2                      90   domestic shorthair         Adoption
3                     365  domestic mediumhair  Return to Owner
4                      21   domestic shorthair         Transfer
5                      60   domestic shorthair         Adoption
6                     240   domestic shorthair         Transfer
7                     150   domestic shorthair         Adoption
8                      60   domestic shorthair         Adoption
9                     365  domestic mediumhair         Transfer
10                     60              siamese         Transfer
11                     14   domestic shorthair         Transfer
12                     60   domestic shorthair         Adoption
13                     90   domestic shorthair         Adoption
14                     21   domestic shorthair         Transfer
15                   1095  domestic mediumhair             Died
16                   1460         russian blue         Adoption
17                    730   domestic shorthair         Transfer
18                   2555         russian blue         Adoption
19                     30   domestic shorthair         Transfer
20                    365  domestic mediumhair         Transfer
21                    730   domestic shorthair         Transfer
22                     60   domestic shorthair         Transfer
23                     28   domestic shorthair         Transfer
24                     90   domestic shorthair         Transfer
25                    365   domestic shorthair         Adoption
26                     60  domestic mediumhair       Euthanasia
27                   2190   domestic shorthair  Return to Owner
28                    730   domestic shorthair         Transfer
29                     14   domestic shorthair       Euthanasia
...                   ...                  ...              ...
29391                3650    domestic longhair         Adoption
29392                6570   american shorthair  Return to Owner
29393                1460   domestic shorthair         Adoption
29394                1460   domestic shorthair         Adoption
29395                  90   domestic shorthair         Adoption
29396                2190    domestic longhair         Adoption
29397                  90  domestic mediumhair         Adoption
29398                1095   domestic shorthair         Adoption
29399                 730   domestic shorthair         Adoption
29400                 730   domestic shorthair  Return to Owner
29401                2555   domestic shorthair  Return to Owner
29402                3650   domestic shorthair         Transfer
29403                4015   domestic shorthair         Adoption
29404                 330  domestic mediumhair         Adoption
29405                1825    domestic longhair         Transfer
29406                 365  domestic mediumhair         Transfer
29407                 365   domestic shorthair         Transfer
29408                 730   domestic shorthair         Transfer
29409                 730   domestic shorthair         Transfer
29410                1095   domestic shorthair         Transfer
29411                 365   domestic shorthair         Transfer
29412                 365   domestic shorthair         Transfer
29413                  90   domestic shorthair       Euthanasia
29414                  60   domestic shorthair         Adoption
29415                 365  domestic mediumhair         Adoption
29416                  60   american shorthair         Adoption
29417                  30   domestic shorthair         Adoption
29418                 365   domestic shorthair         Transfer
29419                 180   domestic shorthair         Adoption
29420                 180  domestic mediumhair         Adoption

[29421 rows x 3 columns]

In [34]:
breed_groups = reduced_df.groupby("breed")
breed_groups["outcome_type"].count()

breed
abyssinian                                    4
american curl shorthair                      11
american shorthair                          211
american wirehair                             1
angora                                       12
angora/persian                                1
balinese                                     10
bengal                                       14
bengal/domestic shorthair                     2
birman                                        2
bombay                                        7
british shorthair                             8
burmese                                       2
chartreux                                     2
cornish rex                                   3
cymric                                        6
devon rex                                     6
domestic longhair                          1273
domestic longhair/domestic longhair           1
domestic longhair/persian                     4
domestic longhair/rex                         2
domestic longhair/russian blue                1
domestic mediumhair                        2454
domestic mediumhair/maine coon                2
domestic mediumhair/manx                      1
domestic mediumhair/siamese                   3
domestic shorthair                        23717
domestic shorthair/abyssinian                 1
domestic shorthair/british shorthair          1
domestic shorthair/domestic mediumhair        1
                                          ...
havana brown                                  1
himalayan                                    38
japanese bobtail                             10
javanese                                      2
maine coon                                  116
manx                                         80
manx/domestic longhair                        2
manx/domestic shorthair                       4
manx/siamese                                  1
munchkin longhair                             2
munchkin shorthair                            2
norwegian forest cat                          4
ocicat                                        1
oriental sh                                   3
persian                                      29
pixiebob shorthair                            4
ragdoll                                      25
russian blue                                 69
scottish fold                                 2
siamese                                    1058
siamese/angora                                1
siamese/domestic shorthair                   13
siamese/japanese bobtail                      3
snowshoe                                    156
snowshoe/domestic shorthair                   1
snowshoe/ragdoll                              2
sphynx                                        3
tonkinese                                     8
turkish angora                                5
turkish van                                   2
Name: outcome_type, Length: 65, dtype: int64